export const BREAKING_KEYWORDS = [
  "breaking",
  "viral",
  "trending",
  "controversy",
  "controversial",
  "backlash",
  "outrage",
  "exposed",
  "leaked",
  "roast",
  "beef",
  "fight",
  "drama",
  "statement",
  "reacts",
  "response",
  "responds",
  "accused",
  "claims",
  "debate",
  "shocking",
  "panic",
  "warning",
  "threat",
  "boycott",
  "cancelled",
  "apology",
  "criticized",
  "slammed",
  "praised",
  "internet reacts",
  "fans react",
  "massive reaction",
  "social media storm",
  "breaking news",
  "big update",
  "latest update",
  "headline",
  "spotlight",
  "livestream",
  "podcast clip",
  "interview",
  "announcement",
  "revealed",
  "deleted post",
  "tweet",
  "instagram story",
  "youtube shorts",
  "stream",
  "online trend",
  "internet sensation",
  "buzz",
  "hot topic",
  "going viral",
];

export const HAPPENING_KEYWORDS = [
  "happening",
  "trending",
  "in news",
  "viral",
  "making headlines",
  "sparks debate",
  "gains attention",
  "reacting",
  "responds",
  "shares",
  "posted",
  "announced",
  "criticized",
  "praised",
  "slammed",
  "accused",
  "involved",
  "discussed",
  "surfaced",
  "revealed",
  "claims",
  "says",
  "reports",
  "launches",
  "collaborates",
  "appears",
  "supports",
  "opposes",
  "comments",
  "opens up",
  "addresses",
  "confirms",
  "denies",
  "apologizes",
  "celebrates",
  "attends",
  "streams",
  "uploads",
  "trends",
  "featured",
];

export const NEWS_KEYWORDS = [
  "snake venom",
  "snake venom case",
  "wildlife act",
  "wildlife protection act",
  "ndps",
  "supreme court",
  "high profile case",
  "criminal proceedings",
  "legal battle",
  "justice prevailed",
  "court verdict",
  "court order",
  "quashed fir",
  "fresh proceedings",

  // Controversies
  "orry",
  "orry row",
  "influencer drama",
  "social media buzz",
  "viral news",
  "breaking news",
  "online controversy",
  "viral controversy",
  "speculation",
  "public response",
  "internet reacts",

  // Creator news
  "bigg boss",
  "bigg boss ott",
  "winner",
  "show appearance",
  "guest appearance",
  "media coverage",
  "press conference",
  "news update",

  // Politics / public discussions
  "political statement",
  "government",
  "minister",
  "election",
  "public issue",
  "national issue",
  // Legal & Court
  "court",
  "high court",
  "supreme court",
  "legal",
  "lawsuit",
  "case",
  "court case",
  "court hearing",
  "petition",
  "notice",
  "summons",
  "fir",
  "police complaint",
  "investigation",
  "under investigation",
  "crime branch",
  "cyber cell",
  "arrest",
  "detained",
  "custody",
  "bail",
  "chargesheet",
  "legal action",
  "defamation",
  "hearing",
  "judge",
  "warrant",

  // Controversy
  "controversy",
  "controversial",
  "backlash",
  "boycott",
  "cancelled",
  "cancel culture",
  "criticism",
  "criticized",
  "criticised",
  "slammed",
  "called out",
  "exposed",
  "allegation",
  "allegedly",
  "accused",
  "response",
  "clarification",
  "statement",
  "public reaction",
  "social media outrage",
  "apology",
  "issue",
  "dispute",
  "conflict",
  "drama",

  // News / Media
  "breaking",
  "exclusive",
  "report",
  "reported",
  "reports",
  "revealed",
  "confirmed",
  "official",
  "officially",
  "announcement",
  "announced",
  "update",
  "latest",
  "news",
  "development",
  "media reports",
  "sources claim",
  "claims",
  "reaction",
  "addressed",

  // Business / Career
  "brand deal",
  "partnership",
  "investment",
  "startup",
  "business",
  "company",
  "acquisition",
  "funding",
  "contract",
  "endorsement",
  "net worth",
  "earnings",

  // Shows / Professional
  "show announcement",
  "season",
  "new show",
  "guest appearance",
  "interview",
  "podcast appearance",
  "award",
  "nomination",
  "winner",
  "netflix",
  "amazon prime",
  "hotstar",
  "television",
  "tv show",

  // Sensitive
  "death",
  "hospital",
  "injury",
  "accident",
  "health update",
  "security issue",
  "threat",
  "attack",
  "fraud",
  "scam",
  "hack",
  "leaked",
  "leak",
  "global",
  "record",
  "failed",
  "socially",
  "emotional",
  "spoke",
  "against",
  "interview",
  "cryptic",
  "note",
  "powerfull",
  "unpredictable",
  "serious",
  "circuit",
  "still alive",
  "opened up",
  "internet",
  "sunil pal",
  "laughter chefs",
];

export const CREATOR_NAMES = [
  {
    name: "Samay_Raina",
    keywords: [
      "samay",
      "samay raina",
      "india's got latent",
      "indias got latent",
      "samay raina controversy",
      "samay raina news",
      "samay raina FIR",
      "samay raina court case",
      "samay raina legal notice",
      "samay raina apology",
      "samay raina comeback",
    ],
    twitterKeyword: ["samay raina latest news"],
    channelName: "@SamayRainaOfficial",
    instagram: "maisamayhoon",
    accentColor: "#a78bfa",
  },
  {
    name: "Elvish_Yadav",
    keywords: [
      "rao sahab",
      "elvishyadav",
      "elvisharmy",
      "elvish",
      "elvishians",
      "elvishsquad",
      "rao_sahab",
      "elvishyadavvlogs",
      "elvishyadavfans",
      "elvishyadavofficial",
      "elvisharmyofficial",
      "elvishbhai",
      "raosahab",
    ],
    twitterKeyword: ["elvish yadav latest news"],
    channelName: "@ElvishYadavVlogs",
    instagram: "elvish_yadav",
    accentColor: "#2dd4a0",
  },
  {
    name: "Urfi_Javed",
    keywords: [
      "uorfi",
      "urfi",
      "urfi javed",
      "urfi javed latest",
      "urfi javed news",
      "urfi javed controversy",
      "urfi javed viral",
      "urfi javed trending",
      "urfi interview",
      "urfi reaction",
      "urfi statement",
      "urfi fashion",
      "urfi outfit",
      "urfi dress",
      "urfi javed instagram",
      "urfi javed youtube",
      "urfi javed twitter",
      "urfi reality show",
      "urfi latest update",
      "urfi javed viral video",
      "urfi javed breaking news",
    ],
    twitterKeyword: ["urfi javed latest news"],
    channelName: "@TheUorfi",
    instagram: "urf7i",
    accentColor: "#f472b6",
  },
  {
    name: "Ranveer_Allahbadia",
    keywords: [
      "ranveer allahbadia",
      "beerbiceps",
      "ranveer allahbadia latest",
      "ranveer allahbadia news",
      "ranveer allahbadia controversy",
      "ranveer allahbadia viral",
      "ranveer allahbadia trending",
      "ranveer allahbadia interview",
      "ranveer allahbadia podcast",
      "ranveer allahbadia reaction",
      "ranveer allahbadia statement",
      "ranveer allahbadia youtube",
      "ranveer allahbadia instagram",
      "beerbiceps podcast",
      "the ranveer show",
      "ranveer allahbadia latest update",
      "ranveer allahbadia breaking news",
      "ranveer allahbadia viral clip",
    ],
    twitterKeyword: ["ranveer allahbadia latest news"],
    channelName: "@beerbiceps",
    instagram: "ranveerallahbadia",
    accentColor: "#f0a830",
  },
  {
    name: "Munawar_Faruqui",
    keywords: [
      "munawar",
      "munawar faruqui",
      "munawar faruqui latest",
      "munawar faruqui news",
      "munawar faruqui controversy",
      "munawar faruqui viral",
      "munawar faruqui reaction",
      "munawar faruqui statement",
      "munawar live",
      "munawar faruqui instagram",
      "munawar faruqui youtube",
      "munawar faruqui twitter",
      "munawar bigg boss",
      "munawar faruqui latest update",
      "munawar faruqui breaking news",
      "munawar faruqui viral",
    ],
    twitterKeyword: ["munawar faruqui latest news"],
    channelName: "@munawar0018",
    instagram: "munawar.faruqui",
    accentColor: "#c084fc",
  },
  {
    name: "Dhruv_Rathee",
    keywords: [
      "dhruv rathee",
      "dhruv rathee latest",
      "dhruv rathee news",
      "dhruv rathee controversy",
      "dhruv rathee viral",
      "dhruv rathee trending",
      "dhruv rathee interview",
      "dhruv rathee reaction",
      "dhruv rathee statement",
      "dhruv rathee youtube",
      "dhruv rathee instagram",
      "dhruv rathee twitter",
      "dhruv rathee politics",
      "dhruv rathee latest video",
      "dhruv rathee latest",
      "dhruv rathee breaking",
      "dhruv rathee viral",
      "dhruv rathee explained",
    ],
    twitterKeyword: ["dhruv rathee latest news"],
    channelName: "@dhruvrathee",
    instagram: "dhruvrathee",
    accentColor: "#e8d44d",
  },
  {
    name: "Ajey_Nagar",
    keywords: [
      "ajey nagar",
      "carryminati",
      "carryminati latest",
      "carryminati news",
      "carryminati controversy",
      "carryminati viral",
      "carryminati trending",
      "carryminati roast",
      "carryminati youtube",
      "carryminati instagram",
      "carryminati gaming",
      "carryislive",
      "carryminati breaking",
    ],
    twitterKeyword: ["carryminati latest news"],
    channelName: "@CarryMinati",
    instagram: "carryminati",
    accentColor: "#1d9bf0",
  },
  {
    name: "Bhuvan_Bam",
    keywords: [
      "bhuvan bam",
      "bbkivines",
      "bhuvan bam latest",
      "bhuvan bam news",
      "bhuvan bam viral",
      "bhuvan bam trending",
      "bhuvan bam interview",
      "bhuvan bam reaction",
      "bhuvan bam youtube",
      "bhuvan bam instagram",
      "bhuvan bam web series",
      "bhuvan bam taaza khabar",
      "bhuvan bam comedy",
      "bhuvan bam breaking",
    ],
    twitterKeyword: ["bhuvan bam latest news"],
    channelName: "@BBKiVines",
    instagram: "bhuvan.bam22",
    accentColor: "#34d399",
  },
  {
    name: "Abhishek_Malhan",
    keywords: [
      "abhishek malhan",
      "fukra insaan",
      "fukrainsaan",
      "abhishek malhan latest",
      "abhishek malhan news",
      "abhishek malhan controversy",
      "abhishek malhan viral",
      "abhishek malhan trending",
      "abhishek malhan statement",
      "fukra insaan latest",
      "fukra insaan youtube",
      "abhishek malhan instagram",
      "fukra insaan vlog",
      "bigg boss ott abhishek malhan",
      "abhishek malhan latest update",
      "abhishek malhan breaking news",
    ],
    twitterKeyword: ["abhishek malhan latest news"],
    channelName: "@FukraInsaan",
    instagram: "fukra_insaan",
    accentColor: "#ff8c42",
  },
  {
    name: "Apoorva_Mukhija",
    keywords: [
      "apoorva mukhija",
      "the rebel kid",
      "rebel kid",
      "apoorva mukhija latest",
      "apoorva mukhija news",
      "apoorva mukhija controversy",
      "apoorva mukhija viral",
      "apoorva mukhija trending",
      "apoorva mukhija interview",
      "apoorva mukhija reaction",
      "apoorva mukhija statement",
      "apoorva mukhija instagram",
      "apoorva mukhija youtube",
      "the rebel kid latest",
      "the rebel kid controversy",
      "india's got latent apoorva",
      "apoorva mukhija breaking",
      "rebel kid news",
    ],
    twitterKeyword: ["apoorva mukhija latest news"],
    channelName: "@the.rebelkid",
    instagram: "the.rebel.kid",
    accentColor: "#f2698a",
  },
];

export const YT_CHANNELS = [
  "AajTak",
  "NewsTak",
  "IndiaToday",
  "TheLallantop",
  "LallantopCinema",
  "NetflixIndiaOfficial",
  "News18India",
  "CNNNews18",
  "IndiaTV",
  "ABPNEWS",
  "ZeeNews",
  "ZeeBharat",
  "TimesNow",
  "TimesNowNavbharat",
  "RepublicWorld",
  "RepublicBharat",
  "NDTV",
  "NDTVIndia",
  "WION",
  "TV9Bharatvarsh",
  "NewsNationTV",
  "News24ThinkFirst",
  "NewsX",
  "IndiaNews",
  "HindustanTimes",
  "ENTLive",
  "RealTalkClips",
  "DesiCrimeStories",
  "BollywoodBubble",
  "Filmygyan",
  "Instant Bollywood",
  "TellyMasala",
  "Pinkvilla",
  "ETimes",
  "ThePrint",
  "Firstpost",
  "India.com",
  "ABP Live",
  "The Quint",
  "Brut India",
  "Saas Bahu Aur Saazish",
  "LiveInsaan",
  "MaiSamayKaPankhaHoon",
  "podcastwala705",
];

export const INSTA_ACCOUNTS = [
  {
    username: "whosthat360",
  },
  {
    username: "indiancreatorclub",
  },
  {
    username: "buzzzookaspotlight",
  },
  {
    username: "filmygyan",
  },
  {
    username: "viralbhayani",
  },
  {
    username: "tcx.official",
  },
  {
    username: "news18india",
  },
  {
    username: "tv9bharatvarsh",
  },
  {
    username: "indiadotcom",
  },
  {
    username: "glamsham",
  },
  {
    username: "samayrainaforever",
  },
];

export const HANDLES = {
  Samay_Raina: ["samayrainaofficial", "realsamayraina", "samayraina"],

  Ranveer_Allahbadia: [
    "beerbiceps",
    "ranveerallahbadia",
    "beerbicepsguy",
    "ranveer",
  ],

  Elvish_Yadav: ["elvishyadav", "elvish_yadav", "elvish"],

  Apoorva_Mukhija: [
    "the.rebel.kid",
    "therebelkid",
    "apoorvamukhija",
    "apoorva",
  ],

  Ajey_Nagar: ["carryminati", "carryislive", "ajeynagar", "carry"],

  Dhruv_Rathee: ["dhruvrathee", "dhruv_rathee", "dhruv"],

  Abhishek_Malhan: [
    "fukra_insaan",
    "fukrainsaan",
    "abhishekmalhan",
    "abhishek",
  ],

  Munawar_Faruqui: [
    "munawar.faruqui",
    "munawar0018",
    "munawarfaruqui",
    "munawar",
  ],

  Urfi_Javed: ["urf7i", "urfijaved", "urfi", "uorfi"],

  Bhuvan_Bam: [
    "bhuvan.bam22",
    "bbkivines",
    "bhuvanbam",
    "bhuvan",
    "bbki vines",
  ],
  Purav_Jha: ["purav jha", "purav"],
};

export const BLOCKED_WORDS = [
  "shorts",
  "short",
  "reel",
  "reels",
  "instagram",
  "youtube",
  "facebook",
  "twitter",
  "news",
  "lifestyle",
  "video",
  "videos",
  "post",
  "posts",
  "channel",
  "creator",
  "content",

  "fukra",
  "insaan",
  "elvishyadav",
  "yadav",
  "elvish",
  "elvisharmy",
  "samay",
  "samayraina",
  "viral",
  "webseries",
  "urfi",
  "raina",
  "allahbadia",
  "ranveer",
  "viralnews",
  "starting",
  "bash",
  "india",
  "indian",
  "different",
  "episode",
  "auto",
  "over",
  "under",
  "through",
  "across",
  "between",
  "within",
  "without",
  "towards",
  "against",
  "around",
  "during",
  "before",
  "after",
  "since",
  "until",
  "while",
  "amid",
  "among",

  "watch",
  "watching",
  "watched",
  "follow",
  "following",
  "like",
  "liked",
  "share",
  "shared",
  "comment",
  "comments",
  "subscribe",

  "get",
  "gets",
  "got",
  "getting",
  "go",
  "goes",
  "went",
  "gone",
  "come",
  "comes",
  "came",
  "whether",

  "new",
  "latest",
  "update",
  "updates",
  "story",
  "stories",
  "full",
  "serving",

  "bro",
  "bros",
  "guy",
  "guys",
  "yaar",
  "bhai",
  "people",
  "someone",
  "everyone",
  "thing",
  "things",
  "kuch",
  "comedy",
  "comedian",
  "trending",
  "entertainment",
];
