export const BREAKING_KEYWORDS = [
  "breaking",
  "viral",
  "trending",
  "controversy",
  "controversial",
  "backlash",
  "outrage",
  "exposed",
  "leaked",
  "roast",
  "beef",
  "fight",
  "drama",
  "statement",
  "reacts",
  "response",
  "responds",
  "accused",
  "claims",
  "debate",
  "shocking",
  "panic",
  "warning",
  "threat",
  "boycott",
  "cancelled",
  "apology",
  "criticized",
  "slammed",
  "praised",
  "internet reacts",
  "fans react",
  "massive reaction",
  "social media storm",
  "breaking news",
  "big update",
  "latest update",
  "headline",
  "spotlight",
  "livestream",
  "podcast clip",
  "interview",
  "announcement",
  "revealed",
  "deleted post",
  "tweet",
  "instagram story",
  "youtube shorts",
  "stream",
  "online trend",
  "internet sensation",
  "buzz",
  "hot topic",
  "going viral",
];

export const HAPPENING_KEYWORDS = [
  "happening",
  "trending",
  "in news",
  "viral",
  "making headlines",
  "sparks debate",
  "gains attention",
  "reacting",
  "responds",
  "shares",
  "posted",
  "announced",
  "criticized",
  "praised",
  "slammed",
  "accused",
  "involved",
  "discussed",
  "surfaced",
  "revealed",
  "claims",
  "says",
  "reports",
  "launches",
  "collaborates",
  "appears",
  "supports",
  "opposes",
  "comments",
  "opens up",
  "addresses",
  "confirms",
  "denies",
  "apologizes",
  "celebrates",
  "attends",
  "streams",
  "uploads",
  "trends",
  "featured",
];

export const NEWS_KEYWORDS = [
  "snake venom",
  "snake venom case",
  "wildlife act",
  "wildlife protection act",
  "ndps",
  "supreme court",
  "high profile case",
  "criminal proceedings",
  "legal battle",
  "justice prevailed",
  "court verdict",
  "court order",
  "quashed fir",
  "fresh proceedings",

  // Controversies
  "orry",
  "orry row",
  "influencer drama",
  "social media buzz",
  "viral news",
  "breaking news",
  "online controversy",
  "viral controversy",
  "speculation",
  "public response",
  "internet reacts",

  // Creator news
  "bigg boss",
  "bigg boss ott",
  "winner",
  "show appearance",
  "guest appearance",
  "media coverage",
  "press conference",
  "news update",

  // Politics / public discussions
  "political statement",
  "government",
  "minister",
  "election",
  "public issue",
  "national issue",
  // Legal & Court
  "court",
  "high court",
  "supreme court",
  "legal",
  "lawsuit",
  "case",
  "court case",
  "court hearing",
  "petition",
  "notice",
  "summons",
  "fir",
  "police complaint",
  "investigation",
  "under investigation",
  "crime branch",
  "cyber cell",
  "arrest",
  "detained",
  "custody",
  "bail",
  "chargesheet",
  "legal action",
  "defamation",
  "hearing",
  "judge",
  "warrant",

  // Controversy
  "controversy",
  "controversial",
  "backlash",
  "boycott",
  "cancelled",
  "cancel culture",
  "criticism",
  "criticized",
  "criticised",
  "slammed",
  "called out",
  "exposed",
  "allegation",
  "allegedly",
  "accused",
  "response",
  "clarification",
  "statement",
  "public reaction",
  "social media outrage",
  "apology",
  "issue",
  "dispute",
  "conflict",
  "drama",

  // News / Media
  "breaking",
  "exclusive",
  "report",
  "reported",
  "reports",
  "revealed",
  "confirmed",
  "official",
  "officially",
  "announcement",
  "announced",
  "update",
  "latest",
  "news",
  "development",
  "media reports",
  "sources claim",
  "claims",
  "reaction",
  "addressed",

  // Business / Career
  "brand deal",
  "partnership",
  "investment",
  "startup",
  "business",
  "company",
  "acquisition",
  "funding",
  "contract",
  "endorsement",
  "net worth",
  "earnings",

  // Shows / Professional
  "show announcement",
  "season",
  "new show",
  "guest appearance",
  "interview",
  "podcast appearance",
  "award",
  "nomination",
  "winner",
  "netflix",
  "amazon prime",
  "hotstar",
  "television",
  "tv show",

  // Sensitive
  "death",
  "hospital",
  "injury",
  "accident",
  "health update",
  "security issue",
  "threat",
  "attack",
  "fraud",
  "scam",
  "hack",
  "leaked",
  "leak",
  "global",
  "record",
  "failed",
  "socially",
  "emotional",
  "spoke",
  "against",
  "interview",
  "cryptic",
  "note",
  "powerfull",
  "unpredictable",
  "serious",
  "circuit",
  "still alive",
  "opened up",
  "internet",
  "sunil pal",
  "laughter chefs",
];

export const CREATOR_NAMES = [
  {
    name: "Samay_Raina",
    keywords: [
      "samay",
      "samay raina",
      "india's got latent",
      "indias got latent",
      "samay raina controversy",
      "samay raina news",
      "samay raina FIR",
      "samay raina court case",
      "samay raina legal notice",
      "samay raina apology",
      "samay raina comeback",
    ],
    twitterKeyword: ["samay raina latest news"],
    channelName: "@SamayRainaOfficial",
    instagram: "maisamayhoon",
    accentColor: "#a78bfa",
  },
  {
    name: "Elvish_Yadav",
    keywords: [
      "rao sahab",
      "elvishyadav",
      "elvisharmy",
      "elvish",
      "elvishians",
      "elvishsquad",
      "rao_sahab",
      "elvishyadavvlogs",
      "elvishyadavfans",
      "elvishyadavofficial",
      "elvisharmyofficial",
      "elvishbhai",
      "raosahab",
    ],
    twitterKeyword: ["elvish yadav latest news"],
    channelName: "@ElvishYadavVlogs",
    instagram: "elvish_yadav",
    accentColor: "#2dd4a0",
  },
  {
    name: "Shreya_Kalra",
    keywords: [
      "Shreya Kalra",
      "shreya kalra latest",
      "shreya kalra news",
      "shreya kalra controversy",
      "shreya kalra viral",
      "shreya kalra trending",
      "shreya kalra interview",
      "shreya kalra reaction",
      "shreya kalra statement",
      "shreya kalra outfit",
      "shreya kalra dress",
      "shreya kalra instagram",
      "shreya kalra youtube",
      "shreya kalra twitter",
      "shreya kalra reality show",
      "shreya kalra latest update",
      "shreya kalra viral video",
      "shreya kalra breaking news",
    ],
    twitterKeyword: ["Shreya Kalra latest news"],
    channelName: "@Shreyakalraa",
    instagram: "shreyakalra",
    accentColor: "#f472b6",
  },
  {
    name: "Varun_Yadav",
    keywords: [
      "Varun Yadav",
      "varun yadav latest",
      "varun yadav news",
      "varun yadav controversy",
      "varun yadav viral",
      "varun yadav trending",
      "varun yadav interview",
      "varun yadav podcast",
      "varun yadav reaction",
      "varun yadav statement",
      "varun yadav youtube",
      "varun yadav instagram",
      "varun yadav podcast",
      "varun yadav latest update",
      "varun yadav breaking news",
      "ranveer viral clip",
    ],
    twitterKeyword: ["Varun Yadav latest news"],
    channelName: "@VarunYadavLailaa",
    instagram: "varun_yadav",
    accentColor: "#f0a830",
  },
  {
    name: "Shivangi_Joshi",
    keywords: [
      "Shivangi Joshi",
      "shivangi joshi latest",
      "shivangi joshi news",
      "shivangi joshi controversy",
      "shivangi joshi viral",
      "shivangi joshi reaction",
      "shivangi joshi statement",
      "Shivangi Joshi instagram",
      "Shivangi Joshi youtube",
      "Shivangi Joshi twitter",
      "Shivangi Joshi latest update",
      "Shivangi Joshi breaking news",
      "Shivangi Joshi viral",
    ],
    twitterKeyword: ["Shivangi Joshi latest news"],
    channelName: "",
    instagram: "Shivangijoshi18",
    accentColor: "#c084fc",
  },
  {
    name: "Akanshka_Choudhary",
    keywords: [
      "akanshka choudhary",
      "akanshka choudhary latest",
      "akanshka choudhary news",
      "akanshka choudhary controversy",
      "akanshka choudhary viral",
      "akanshka choudhary trending",
      "akanshka choudhary interview",
      "akanshka choudhary reaction",
      "akanshka choudhary statement",
      "akanshka choudhary youtube",
      "akanshka choudhary instagram",
      "akanshka choudhary twitter",
      "akanshka choudhary politics",
      "akanshka choudhary latest video",
      "akanshka choudhary latest",
      "akanshka choudhary breaking",
      "akanshka choudhary viral",
      "akanshka choudhary explained",
    ],
    twitterKeyword: ["Akanshka Choudhary latest news"],
    channelName: "@Akankshachoudhary_official",
    instagram: "akanksachoudhary_official",
    accentColor: "#e8d44d",
  },
  {
    name: "Kushan_Tandon",
    keywords: [
      "Kushan Tandon",
      "Kushan Tandon latest",
      "Kushan Tandon news",
      "Kushan Tandon controversy",
      "Kushan Tandon viral",
      "Kushan Tandon trending",
      "Kushan Tandon roast",
      "Kushan Tandon youtube",
      "Kushan Tandon instagram",
      "Kushan Tandon gaming",
      "Kushan Tandon islive",
      "Kushan Tandon breaking",
    ],
    twitterKeyword: ["Kushan Tandon latest news"],
    channelName: "",
    instagram: "therealkushaltandon",
    accentColor: "#1d9bf0",
  },
  {
    name: "Vanshaj_Singh",
    keywords: [
      "vanshaj singh",
      "vanshaj singh latest",
      "vanshaj singh news",
      "vanshaj singh viral",
      "Vanshaj Singh trending",
      "Vanshaj Singh interview",
      "Vanshaj Singh reaction",
      "Vanshaj Singh youtube",
      "Vanshaj Singh instagram",
      "Vanshaj Singh web series",
      "Vanshaj Singh taaza khabar",
      "Vanshaj Singh comedy",
      "Vanshaj Singh breaking",
    ],
    twitterKeyword: ["Vanshaj Singh latest news"],
    channelName: "@iamvanshajsingh",
    instagram: "iamvanshajsingh",
    accentColor: "#34d399",
  },
  {
    name: "Payal_Dhare",
    keywords: [
      "Payal Dhare",
      "Payal Gaming",
      "Payal Dhare latest",
      "Payal Dhare news",
      "Payal Dhare controversy",
      "Payal Dhare viral",
      "Payal Dhare trending",
      "Payal Dhare statement",
      "Payal Gaming latest",
      "Payal Gaming youtube",
      "Payal Dhare instagram",
      "Payal Gaming vlog",
      "Payal Dhare latest update",
      "Payal Dhare breaking news",
    ],
    twitterKeyword: ["Payal Dhare latest news"],
    channelName: "@PAYALGAMING",
    instagram: "payalgamingg",
    accentColor: "#ff8c42",
  },
  {
    name: "Apoorva_Mukhija",
    keywords: [
      "apoorva mukhija",
      "the rebel kid",
      "rebel kid",
      "apoorva mukhija latest",
      "apoorva mukhija news",
      "apoorva mukhija controversy",
      "apoorva mukhija viral",
      "apoorva mukhija trending",
      "apoorva mukhija interview",
      "apoorva mukhija reaction",
      "apoorva mukhija statement",
      "apoorva mukhija instagram",
      "apoorva mukhija youtube",
      "the rebel kid latest",
      "the rebel kid controversy",
      "india's got latent apoorva",
      "apoorva mukhija breaking",
      "rebel kid news",
    ],
    twitterKeyword: ["apoorva mukhija latest news"],
    channelName: "@the.rebelkid",
    instagram: "the.rebel.kid",
    accentColor: "#f2698a",
  },
];

export const YT_CHANNELS = [
  "AajTak",
  "NewsTak",
  "IndiaToday",
  "TheLallantop",
  "LallantopCinema",
  "NetflixIndiaOfficial",
  "News18India",
  "CNNNews18",
  "IndiaTV",
  "ABPNEWS",
  "ZeeNews",
  "ZeeBharat",
  "TimesNow",
  "TimesNowNavbharat",
  "RepublicWorld",
  "RepublicBharat",
  "NDTV",
  "NDTVIndia",
  "WION",
  "TV9Bharatvarsh",
  "NewsNationTV",
  "News24ThinkFirst",
  "NewsX",
  "IndiaNews",
  "HindustanTimes",
  "ENTLive",
  "RealTalkClips",
  "DesiCrimeStories",
  "BollywoodBubble",
  "Filmygyan",
  "Instant Bollywood",
  "TellyMasala",
  "Pinkvilla",
  "ETimes",
  "ThePrint",
  "Firstpost",
  "India.com",
  "ABP Live",
  "The Quint",
  "Brut India",
  "Saas Bahu Aur Saazish",
  "LiveInsaan",
  "MaiSamayKaPankhaHoon",
  "podcastwala705",

  "TellyReporter",
  "tellychakkar",
  "tellymasala",
  "filmibeat",
  "EditMosaicmedia",
  "TruthSlayer_24",
  "shivangijoshiprofessional",
  "filmygyanvideos",
];

export const INSTA_ACCOUNTS = [
  {
    username: "whosthat360",
  },
  {
    username: "indiancreatorclub",
  },
  {
    username: "buzzzookaspotlight",
  },
  {
    username: "filmygyan",
  },
  {
    username: "viralbhayani",
  },
  {
    username: "tcx.official",
  },
  {
    username: "news18india",
  },
  {
    username: "tv9bharatvarsh",
  },
  {
    username: "indiadotcom",
  },
  {
    username: "glamsham",
  },
  {
    username: "samayrainaforever",
  },

  {
    username: "webseriesmaina",
  },
  {
    username: "reality_scoop_",
  },
  {
    username: "film.window",
  },
  {
    username: "reality_showwz",
  },
  {
    username: "tellyreporter",
  },
  {
    username: "kiddaanentertainment",
  },
  {
    username: "delhixgang",
  },
  {
    username: "shivi.momo_forever_05",
  },
  {
    username: "allianceshow_official",
  },
  {
    username: "reality_flicks_",
  },
  {
    username: "realitywibes",
  },
  {
    username: "alliance_primeofficial",
  },
  {
    username: "payal.alliance",
  },
];

export const HANDLES = {
  Samay_Raina: ["samayrainaofficial", "realsamayraina", "samayraina"],

  Elvish_Yadav: ["elvishyadav", "elvish_yadav", "elvish"],

  Shreya_Kalra: ["Shreya Kalra", "shreyakalra", "Shreya", "Kalra"],

  Varun_Yadav: ["Varun Yadav", "varunyadav", "Varun", "Yadav", "Laila"],

  Shivangi_Joshi: ["Shivangi Joshi", "shivangijoshi", "Shivangi", "Joshi"],

  Akanshka_Choudhary: [
    "Akanshka Choudhary",
    "akanshkachoudhary",
    "Akanshka",
    "Choudhary",
  ],

  Kushan_Tandon: ["Kushan Tandon", "kushantandon", "Kushan", "Tandon"],

  Vanshaj_Singh: ["Vanshaj Singh", "vanshajsingh", "Vanshaj", "Singh"],

  Apoorva_Mukhija: [
    "the.rebel.kid",
    "therebelkid",
    "apoorvamukhija",
    "apoorva",
    "mukhija",
  ],
  Payal_Dhare: ["Payal Dhare", "payaldhare", "Payal", "Dhare"],
};

export const BLOCKED_WORDS = [
  "shorts",
  "short",
  "reel",
  "reels",
  "instagram",
  "youtube",
  "facebook",
  "twitter",
  "news",
  "lifestyle",
  "video",
  "videos",
  "post",
  "posts",
  "channel",
  "creator",
  "content",

  "fukra",
  "insaan",
  "elvishyadav",
  "yadav",
  "elvish",
  "elvisharmy",
  "samay",
  "samayraina",
  "viral",
  "webseries",
  "urfi",
  "raina",
  "allahbadia",
  "ranveer",
  "viralnews",
  "starting",
  "bash",
  "india",
  "indian",
  "different",
  "episode",
  "auto",
  "over",
  "under",
  "through",
  "across",
  "between",
  "within",
  "without",
  "towards",
  "against",
  "around",
  "during",
  "before",
  "after",
  "since",
  "until",
  "while",
  "amid",
  "among",

  "watch",
  "watching",
  "watched",
  "follow",
  "following",
  "like",
  "liked",
  "share",
  "shared",
  "comment",
  "comments",
  "subscribe",

  "get",
  "gets",
  "got",
  "getting",
  "go",
  "goes",
  "went",
  "gone",
  "come",
  "comes",
  "came",
  "whether",

  "new",
  "latest",
  "update",
  "updates",
  "story",
  "stories",
  "full",
  "serving",

  "bro",
  "bros",
  "guy",
  "guys",
  "yaar",
  "bhai",
  "people",
  "someone",
  "everyone",
  "thing",
  "things",
  "kuch",
  "comedy",
  "comedian",
  "trending",
  "entertainment",
];
